name: Build and deploy Python project to Azure Function App - GetVisitorCount

on:
  push:
    branches:
      - main
  workflow_dispatch:

# REMOVE permissions block entirely, as it's not needed for Publish Profile
# We do not want to use OIDC permissions for this method.

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: 'backend-function'
  PYTHON_VERSION: '3.12' 

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python version
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate
        working-directory: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}

      - name: Install dependencies
        run: pip install -r requirements.txt
        working-directory: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}

      - name: Zip artifact for deployment
        run: zip -r release.zip ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/. -x *venv*

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    # No explicit permissions block needed here

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app
          path: deployment-artifact

      - name: Unzip artifact for deployment
        run: |
          unzip deployment-artifact/release.zip
          rm deployment-artifact/release.zip
        
      # CRITICAL CHANGE: REMOVE the old 'Login to Azure' step entirely.

      - name: 'Deploy to Azure Functions'
        uses: Azure/functions-action@v1
        with:
          app-name: 'dane-resume-api-prod' # Your NEW Function App Name
          package: . 
          # NEW LINE: Authenticate using the Publish Profile Secret
          publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
